sudo: required

node_js:
  - "7"
  - "6"
  - "4"

services:
  - docker

cache:
  directories:
    - node_modules

install:
  - docker-compose run --rm cli yarn install

script:
  - docker-compose run --rm cli tsc

after_success:
  - npm run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/